### ISSUE TITLE
Build a Production Concept Model (Iteration 1)

### ISSUE THREAD

**Issue by SnorreFossland** [Kavca/osdu-akm-models#18]
# Production Concept Model

# Tasks to be done in the first iteration

- [x] Create a new model based on the new AKM Core and IRTV template

- [ ] Build a P&ID like modelview for understanding the Product-model
(updated Oct. 26 in meeting with Einar, Frank and Snorre)

![Screenshot 2023-10-26 at 17 39 27](https://github.com/Kavca/osdu-akm-models/assets/31763773/702a379b-3645-478d-9781-1e60bf6fba86)

- [x] Recreate the previous models as Concept Models (IRTV)
(updated Oct. 26 in meeting with Einar, Frank and Snorre)
![Screenshot 2023-10-26 at 17 43 48](https://github.com/Kavca/osdu-akm-models/assets/31763773/bd53a030-eb7e-4ae1-875e-4e9fd0c94cf0)

- [ ] Agree upon type by adding suggestedType to Information Objects.
(updated Oct. 26 after meeting with Einar, Frank and Snorre)

Showing Role, Tasks and suggested Types for Production test.
![Screenshot 2023-10-26 at 17 48 20](https://github.com/Kavca/osdu-akm-models/assets/31763773/5a3d7d26-d6bc-4072-9138-7f7884f631cd)

**Comment by SnorreFossland** [comment]
# Previous Modelling work done by Bjørn and Snorre

## Types and Properties from ProdML example-file

This is a interpretation of the ProdML example file.  URL........

![Image](https://github.com/Kavca/osdu-akm-models/assets/31763773/6055a469-20f5-4fb6-a03e-f722d6bffc04)

---

(zoomed in upper part)

![Image](https://github.com/Kavca/osdu-akm-models/assets/31763773/451df498-981e-4879-8ae5-787950a1388f)


(zoomed in lower part)
![Image](https://github.com/Kavca/osdu-akm-models/assets/31763773/8a519d84-0809-4384-b926-6220d77742d4)



## ProdML Example
![Image](https://github.com/Kavca/osdu-akm-models/assets/31763773/d507c315-c295-483e-923a-5cab52f2eb27)



## Production Test Models



![Image](https://github.com/Kavca/osdu-akm-models/assets/31763773/a9b07fdc-db79-4193-98e4-a5b7a4593e8f)



![Image](https://github.com/Kavca/osdu-akm-models/assets/31763773/2d351fd4-1e8a-42b6-8357-ff45b56354ae)

**Comment by franklillehagen** [comment]
Snorre og Bjørn,

Will it be possible to model and present views of well measures and flows, and show how these measures influences the well design and drilling, and the oil production?
I will study this more!
Frank

**Comment by SnorreFossland** [comment]
# Well / Facility test (first unfinished attempt. will be updated) 

## Here is some generic tasks and types for Well/Productions tests:

![Screenshot 2023-10-19 at 11 44 35](https://github.com/Kavca/osdu-akm-models/assets/31763773/7ca74f65-a436-4f93-bc5d-96f81942869e)

The information objects has suggested type which we need to discuss and agree upon. It probably needs to be synchronized with OSDU schema types (naming etc.)

 
## Here is the re-implemented  test-example of the model Bjørn and I did in February

(still missing some relationships. Will be updated )

![Screenshot 2023-10-19 at 11 28 35](https://github.com/Kavca/osdu-akm-models/assets/31763773/539d34c1-ac85-4cac-8657-f2cb811c9b6e)

**Comment by SnorreFossland** [comment]
# P&ID like model built in friday meeting:

![Screenshot 2023-10-20 at 13 55 44](https://github.com/Kavca/osdu-akm-models/assets/31763773/fab984cb-f34c-4acc-9cd0-f467c9495b2a)

**Comment by SnorreFossland** [comment]
# test av svg-file

![figtest](https://raw.githubusercontent.com/Kavca/osdu-akm-models/0c24b4be5b82337ec0eded4390dcaad0cb4fd1f1/doc/AKM-Type-Definitions_Production-Test_CM_2-P%26ID%20(1).svg)

**Comment by franklillehagen** [comment]
Snorre,
Do we need a Production Manager to perform planning of the Welltesting, and the management of the FiscalRate?
This role may also be responsible for calculating and sharing the Fieldfactor.

**Comment by franklillehagen** [comment]
Bjørn og Snorre,

Dette bør vel bli en en god metodikk med 3-4 samspillende modeller: - wellbore product design, well testing, test log management, well test results og (sampled?) og production values.
Vi må formidle samspillet mellom roller og testresultater for disse stegene.
Dette er en lovende start!
 
Frank
